version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: auth.dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ponderada3
    ports:
      - "5432:5432"

  image_processing:
    build:
      context: .
      dockerfile: image.dockerfile  # Dockerfile para o serviço de processamento de imagem
    ports:
      - "8000:8000"  # Porta para o serviço de processamento de imagem
    depends_on:
      - db