services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - service1
      - service2
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  service1:
    build: ./service1
    ports:
      - "5001:5001"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  service2:
    build: ./service2
    ports:
      - "5002:5002"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    volumes:
      - ./logs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
